name: ci

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.9"
          enable-cache: true

      - name: Check style
        run: uvx ruff check

      - name: Run tests
        env:
          CI: true
        run: |
          uv run pytest
